//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class newarrival
    {
        public int id { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> order { get; set; }
        public string img { get; set; }
        public string status { get; set; }
        public string sell { get; set; }
        public string pire { get; set; }
        public string name { get; set; }
        public Nullable<int> product_id { get; set; }
        public string link { get; set; }
        public Nullable<System.DateTime> databegin { get; set; }
    
        public virtual product product { get; set; }
    }
}
