//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderdetail
    {
        public int id { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<int> product { get; set; }
        public Nullable<int> quantily { get; set; }
    
        public virtual order order1 { get; set; }
        public virtual product product1 { get; set; }
    }
}
